spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  kafka:
      bootstrap-servers: ${ENV_KAFKA_BOOTSTRAP_SERVERS}
      producer:
        retries: 0
logging:
  level:
    org.apache.kafka: INFO