/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package kafka.rest.admin

import spock.lang.Specification

class ApplicationTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new Application()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
